In [1]:
import numpy as np

Create and inspect an array

In [2]:
mon_array=np.array([1,2,4,6])
print mon_array
print mon_array.shape
print mon_array.dtype

[1 2 4 6]
(4L,)
int32


Build an array with zero

In [3]:
zero_array=np.ones(10)
print zero_array

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


Build an array with a range from 5 with 15 values and a step of 2

In [4]:
arr1=np.arange(5,35,2)
arr1

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

Build an array with a range starting with 50 with values until 10 with a step of 2

In [5]:
arr2=np.arange(50,8,-2)
arr2

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10])

Compute the cube of the array

In [6]:
arr2**3

array([125000, 110592,  97336,  85184,  74088,  64000,  54872,  46656,
        39304,  32768,  27000,  21952,  17576,  13824,  10648,   8000,
         5832,   4096,   2744,   1728,   1000])

In [7]:
arr2=np.array(range(9))
arr3=arr2[1:7]
print arr3

[1 2 3 4 5 6]


Create a 3 by 2 array and compute X'X 

In [8]:
arr4=np.arange(5,11).reshape((3,2))
print np.dot(arr4.T,arr4)

[[155 176]
 [176 200]]


Generate a random array using a normal distribution and replace all negative values by 0

In [9]:
arr5 =np.random.randn(100)
arr6=np.where(arr5>0,arr5,0)
print np.sort(arr6)

[ 0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.00544647  0.04182297
  0.04572631  0.06211214  0.09332561  0.11169864  0.16414998  0.19324986
  0.22308921  0.22759917  0.22837319  0.29042376  0.33030754  0.35689275
  0.39239531  0.40469366  0.44278748  0.48859298  0.51516828  0.55160231
  0.55525913  0.56961161  0.57323509  0.60412733  0.69683611  0.8263158
  0.82667868  0.8435

Create a large 10000 x 10 array and export it as .npy and .txt

In [10]:
arr7=np.random.randn(100000).reshape(10000,10)
np.save("arr7.npy",arr7)
np.savetxt('arr7.txt', arr7, delimiter=';')